### ISSUE TITLE
saveAsWarc compressed file

### ISSUE THREAD

**Issue by dportabella** [helgeho/ArchiveSpark#11]
This code produces a .cdx and .warc file.
```
ArchiveSpark.load(sc, WarcCdxHdfsSpec(cdxPath = "/data/example.cdx.gz", warcPath = "/data"))
.filter(r => r.surtUrl.startsWith("com,example"))
.saveAsWarc("/tmp/filtered_warc", WarcMeta(), generateCdx = true)
```
would it be possible to directly produce a cdx.gz and warc.gz file?

**Comment by helgeho** [comment]
Just add .gz to your destination directory and it will create compressed WARC and CDX files.
