### ISSUE TITLE
unresolved dependency for hadoop-core

### ISSUE THREAD

**Issue by parismic** [helgeho/ArchiveSpark#16]
When building with sbt 0.13.16 the ArchiveSpark 2.7.6 version with scala 2.11.7 the following error occurs.

> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	::          UNRESOLVED DEPENDENCIES         ::
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	:: org.apache.hadoop#hadoop-core;0.20.2-cdh3u4: not found
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::

> [warn] 		org.apache.hadoop:hadoop-core:0.20.2-cdh3u4
> [warn] 		  +- org.netpreserve.commons:webarchive-commons:1.1.8
> [warn] 		  +- com.github.helgeho:hadoop-concat-gz:1.2.2
> [warn] 		  +- com.github.helgeho:archivespark_2.11:2.7.6 (/myproject/build.sbt#L14-15)
> [warn] 		  +- default:initialdiagnosisgaw_2.11:0.1

**Comment by helgeho** [comment]
please check out v.3.0, this should be resolved now
