### ISSUE TITLE
saveAsWarc() does not reproduce input

### ISSUE THREAD

**Issue by parismic** [helgeho/ArchiveSpark#18]
Three Sample WARC records (in the ArchiveSpark sense) are presented;

```
WARC/1.0
WARC-Type: response
WARC-Target-URI: http://udk-berlin.de/
WARC-Date: 2015-12-15T09:43:03Z
WARC-Payload-Digest: sha1:QH732FYSV7UM34JYWVYMB7EZGR2CYM6B
WARC-IP-Address: 194.95.94.100
WARC-Record-ID: <urn:uuid:9d5d3092-2b0e-4f57-968e-0f62f6797817>
Content-Type: application/http; msgtype=response
Content-Length: 367

HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 15 Dec 2015 09:43:02 GMT
Content-Type: text/html
Content-Length: 178
Connection: close
Location: https://www.udk-berlin.de/

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>


WARC/1.0
WARC-Type: request
WARC-Target-URI: http://udk-berlin.de/
WARC-Date: 2015-12-15T09:43:03Z
WARC-Concurrent-To: <urn:uuid:9d5d3092-2b0e-4f57-968e-0f62f6797817>
WARC-Record-ID: <urn:uuid:fba408fa-f9d5-4b36-ae13-48c7ff80787d>
Content-Type: application/http; msgtype=request
Content-Length: 236

GET / HTTP/1.0
User-Agent: Mozilla/5.0 (compatible; heritrix/3.1.0 +http://www.kbs.uni-hannover.de/~jaeschke/crawler/)
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Host: udk-berlin.de



WARC/1.0
WARC-Type: metadata
WARC-Target-URI: http://udk-berlin.de/
WARC-Date: 2015-12-15T09:43:03Z
WARC-Concurrent-To: <urn:uuid:9d5d3092-2b0e-4f57-968e-0f62f6797817>
WARC-Record-ID: <urn:uuid:30a62694-7bf6-48d4-8a4f-7976dfcc5a0e>
Content-Type: application/warc-fields
Content-Length: 135

seed:
fetchTimeMs: 13
outlink: http://udk-berlin.de/favicon.ico I =INFERRED_MISC
outlink: https://www.udk-berlin.de/ R Location:
```

When loading the `RDD` and one saves the unaltered `RDD[WarcRecord]` with `saveAsWarc the output does not match the original WARC-records. 
```
val RDD = ArchiveSpark.load(WarcCdxHdfsSpec(cdxPath, warcPath))
RDD.saveAsWarc(filePath + "warc.gz",WarcMeta(publisher = "Author"), generateCdx = true)
```
Examples:
1. Only the last `outlink` in the record with `WARC-Type: metadata` is saved. 

The corresponding CDX record is what apparently ArchiveSpark regards as metadata [(bottom of comment)](https://github.com/helgeho/ArchiveSpark/issues/5#issuecomment-333131486). I think this is an inappropriate description. ArchiveSpark uses, as long as there is no enrichment, only the CDX-records. 

As soon as an enrichment takes place the `WarcPayload` enrichment is created and the fields in what is considered an `httpHeader` are populated in `HttpResponse.scala` at [62-64](https://github.com/helgeho/ArchiveSpark/blob/3fd98e21742c00b3d4bf758aaeb1a5962a04ba63/src/main/scala/de/l3s/archivespark/http/HttpResponse.scala#L62-L64). This can not work with fields that have the same name. One possible work-around is to call `access` on a WarcRecord during a map and dig down to this problem.

```
    val recordMapList = rdd.map(r => r.access[mutable.Map[String, List[String]]]{s =>
        var httpResponse: InputStream = null
        val bytes = s.payload
        try {
        val parser = new HttpResponseParser
        httpResponse = new ByteArrayInputStream(bytes)
        val response = parser.parse(httpResponse)
        val httpHeaders = response.getHeaders
        val header = collection.mutable.Map[String, List[String]]()
        for (httpHeader <- httpHeaders.iterator().asScala) {
            if (header.contains(httpHeader.getName)){
                val oldkey=httpHeader.getName
                val newValue=httpHeader.getValue
                var newList = header(httpHeader.getName)
                newList ::= newValue
                header.put(oldkey, newList)
            } else {
                header.put(httpHeader.getName, List(httpHeader.getValue))
            }
        }
        header}finally {
            if (httpResponse != null) httpResponse.close()
        }
    })
```
This is a possible solution to generally avoid dealing with `WarcPayload`.

2. All records after saving are now `WARC-Type: response`

This is just unexpected that [WarcRDD at SparkIO.save](https://github.com/helgeho/ArchiveSpark/blob/3fd98e21742c00b3d4bf758aaeb1a5962a04ba63/src/main/scala/de/l3s/archivespark/specific/warc/implicits/WarcRDD.scala#L85) considers every `recordHeader` to be from a [responseRecord](https://github.com/helgeho/ArchiveSpark/blob/3fd98e21742c00b3d4bf758aaeb1a5962a04ba63/src/main/scala/de/l3s/archivespark/specific/warc/WarcHeaders.scala#L72). The problem is that there is a certain idea contained within ArchiveSpark what a WarcRecords is. This idea seems incomplete and needs to be fixed at a IO level. One possible approach could be the use of `WARC-Record-ID` and `WARC-Concurrent-To` fields to link WarcRecords or at least for now a version of [WarcHeader.scala](https://github.com/helgeho/ArchiveSpark/blob/master/src/main/scala/de/l3s/archivespark/specific/warc/WarcHeaders.scala) which is not hard coded but dependent.

**Comment by helgeho** [comment]
Thanks Michael, these are excellent points and indeed, ArchiveSpark or at least ArchiveSpark's included WARC dataspec was designed to work with response records only, even though that has never been made explicit and you could theoretically use it with other types as well. Therefore, all methods provided with it, like `saveAsWarc`, were designed with that in mind. You could, with little effort write your own dataspec that use a completely independent set of record classes and methods, but still uses ArchiveSpark's internal datamodel and enrichment mechanisms. I totally agree, that this should be part of the core framework though, which would require additional flags in the records objects, like its type.

Thanks for the suggestions and I'll get in touch to discuss this offline!

**Comment by helgeho** [comment]
please check out v.3.0, this should be resolved now
