### ISSUE TITLE
java.lang.ClassNotFoundException: io.circe.Json

### ISSUE THREAD

**Issue by parismic** [helgeho/ArchiveSpark#20]
Using the maven jar, the following error occurs.

```
val WarcRDD = ArchiveSpark.load(WarcCdxHdfsSpec(cdxPath, warcPath))
WarcRDD.take(4)
java.lang.NoClassDefFoundError: io/circe/Json
....
Caused by: java.lang.ClassNotFoundException: io.circe.Json
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
```

This error does not occur in the version 2.7.6

**Comment by helgeho** [comment]
Circe is the new JSON library we added in 3.0. If you simply download the JAR from maven central, it typically does not include dependencies. So, either use a build tool like Maven or SBT, manually download required dependencies, or get the dependencies JAR from our release https://github.com/helgeho/ArchiveSpark/releases/tag/v.3.0
