### ISSUE TITLE
load a warc archive without a cdx file

### ISSUE THREAD

**Issue by dportabella** [helgeho/ArchiveSpark#9]
this code effectively loads the CDX index, and gets the warc pages if needed.
`val rdd: RDD[WarcRecord] = ArchiveSpark.load(sc, WarcCdxHdfsSpec("/data/example.cdx.gz", "/data"))`

I see that definition of `ArchiveSpark.load(sc: SparkContext, spec: DataSpec[Raw, Parsed]): RDD[Parsed]`, and I see that there are several implementations of DataSpec, but all the Warc one require a CDX file.

Is it possible to load a warc archive without a CDX file? how?

**Comment by helgeho** [comment]
Hi David,

ArchiveSpark's efficiency comes through its two-step loading approach. It first loads the metadata from CDX, which is lightweight and fast, you can then apply filters to it, or group, or sort it, etc., and only then, when you call enrich, it will integrate the actual data from the WARC files. If you directly work with WARCs it would be much slower, as it needs to load parse every single record, even if you don't need it for you analysis and will filter it out. That's the core concept of ArchiveSpark.

However, in the coming version there will be a DataSpec to load raw WARCs in two different formats. The main purpose of this is to generate CDX files though.

**Comment by dportabella** [comment]
Ok, thx!
I see that you have different `DataSpec` implementation, but I don't see an explanation about them.
To use a file from s3n, can I simply use `WarcCdxHdfsSpec` and pass string like this `s3n://commoncrawl/crawl-data/CC-MAIN-2016-36/segments/1471982290442.1/warc/`?

**Comment by helgeho** [comment]
The `WarcCdxHdfsSpec` uses Hadoop's filesystem classes, I am not sure if they support s3n, if so this should work, but you always need CDX as well.

**Comment by helgeho** [comment]
This is possible now, please read https://github.com/helgeho/ArchiveSpark/blob/master/docs/DataSpecs.md for an overview of available DataSpecs.

A concrete example loading WARCs without CDX is available here:
https://github.com/helgeho/ArchiveSpark/blob/master/notebooks/Generate_CDX.ipynb
